import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:open_filex/open_filex.dart';
import '../providers/app_state.dart';

class ReportPreviewScreen extends StatelessWidget {
  const ReportPreviewScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF0F4F8),
      appBar: AppBar(
        title: Text('Executive Report', style: GoogleFonts.inter(fontWeight: FontWeight.w600)),
        actions: [
          IconButton(
            icon: const Icon(FontAwesomeIcons.shareNodes, size: 18),
            onPressed: () {
               ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Share functionality simulated')));
            },
          ),
          IconButton(
            icon: const Icon(FontAwesomeIcons.download, size: 18),
            onPressed: () => _generatePdf(context),
            // onPressed: () {
            //    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('PDF Download simulated')));
            // },
          ),
        ],
      ),
      body: Consumer<AppState>(
        builder: (context, state, _) {
          final data = state.agentResults['report_generator'];
          
          if (data == null) {
            return Center(child: Text("No report data available.", style: GoogleFonts.inter(color: Colors.grey)));
          }

          return SingleChildScrollView(
            padding: const EdgeInsets.all(24),
            child: Column(
              children: [
                // Report Paper
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(40),
                  decoration: BoxDecoration(
                    color: Colors.white,
                    boxShadow: [
                      BoxShadow(color: Colors.black.withValues(alpha: 0.1), blurRadius: 20, offset: const Offset(0, 10)),
                    ],
                  ),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Header
                      Center(
                        child: Column(
                          children: [
                            const Icon(FontAwesomeIcons.dna, size: 32, color: Color(0xFF0056D2)),
                            const SizedBox(height: 16),
                            Text(
                              'PHARMA STRATEGIC INTELLIGENCE',
                              style: GoogleFonts.inter(
                                fontSize: 12, 
                                fontWeight: FontWeight.w700, 
                                letterSpacing: 2.0,
                                color: const Color(0xFF486581)
                              ),
                            ),
                            const SizedBox(height: 8),
                            Text(
                              'Executive Briefing',
                              style: GoogleFonts.playfairDisplay( // Use Playfair for "Report" feel if avail, else fallback
                                fontSize: 32,
                                fontWeight: FontWeight.bold,
                                color: const Color(0xFF102A43),
                              ),
                            ),
                            const SizedBox(height: 8),
                            Text(
                              'Generated by Cureonix AI • ${DateTime.now().toString().split(' ')[0]}',
                              style: GoogleFonts.inter(color: Colors.grey[500], fontSize: 12),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 48),
                      
                      const Divider(thickness: 2, color: Color(0xFF0056D2)),
                      const SizedBox(height: 32),

                      // Summary
                      Text("EXECUTIVE SUMMARY", style: _headingStyle()),
                      const SizedBox(height: 12),
                      Text(
                        data['summary'] ?? '',
                        style: GoogleFonts.merriweather( // Serif for report body
                          fontSize: 14, 
                          height: 1.8, 
                          color: const Color(0xFF334E68)
                        ),
                      ),
                      
                      const SizedBox(height: 32),

                      // Tables if any
                      if (data['tables'] != null)
                        ...(data['tables'] as List).map((t) {
                          return Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text((t['title'] ?? 'Key Data').toUpperCase(), style: _headingStyle()),
                              const SizedBox(height: 12),
                              _buildTable(t),
                              const SizedBox(height: 32),
                            ],
                          );
                        }),
                      
                      const SizedBox(height: 48),
                      Center(
                        child: Text(
                          "CONFIDENTIAL - INTERNAL USE ONLY",
                          style: GoogleFonts.inter(fontSize: 10, color: Colors.grey[400], letterSpacing: 1.0),
                        ),
                      )
                    ],
                  ),
                ),
                const SizedBox(height: 40),
                ElevatedButton.icon(
                  onPressed: () => _generatePdf(context),
                  icon: const Icon(FontAwesomeIcons.filePdf),
                  label: const Text("Download Full PDF"),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF102A43),
                    padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                  ),
                ),
                const SizedBox(height: 40),
              ],
            ),
          );
        },
      ),
    );
  }

  TextStyle _headingStyle() {
    return GoogleFonts.inter(
      fontSize: 12, 
      fontWeight: FontWeight.w800, 
      color: const Color(0xFF0056D2), 
      letterSpacing: 1.0
    );
  }

  Widget _buildTable(dynamic tableData) {
     List<String> headers = List<String>.from(tableData['headers'] ?? []);
     List<dynamic> rows = tableData['rows'] ?? [];

     return Table(
       border: TableBorder.all(color: Colors.grey[200]!),
       children: [
         TableRow(
           decoration: const BoxDecoration(color: Color(0xFFF0F4F8)),
           children: headers.map((h) => Padding(
             padding: const EdgeInsets.all(8.0),
             child: Text(h, style: GoogleFonts.inter(fontWeight: FontWeight.bold, fontSize: 11)),
           )).toList(),
         ),
         ...rows.map((r) {
           return TableRow(
             children: (r as List).map((cell) => Padding(
               padding: const EdgeInsets.all(8.0),
               child: Text(cell.toString(), style: GoogleFonts.inter(fontSize: 12)),
             )).toList(),
           );
         })
       ],
     );
  }


  Future<void> _generatePdf(BuildContext context) async {
     final state = Provider.of<AppState>(context, listen: false);
     final data = state.agentResults['report_generator'];
     if (data == null) {
       ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('No data to export')));
       return;
     }

     final pdf = pw.Document();

     pdf.addPage(
       pw.MultiPage(
         pageFormat: PdfPageFormat.a4,
         build: (pw.Context context) {
           return [
             pw.Header(
               level: 0,
               child: pw.Row(
                 mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                 children: [
                   pw.Text('Cureonix Intelligence', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                   pw.Text('Confidential', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                 ]
               )
             ),
             pw.SizedBox(height: 20),
             pw.Text('Executive Summary', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.blue)),
             pw.SizedBox(height: 10),
             pw.Text(data['summary'] ?? 'No summary provided.'),
             pw.SizedBox(height: 20),
             if (data['tables'] != null)
               ...(data['tables'] as List).map((t) {
                 final headers = List<String>.from(t['headers'] ?? []);
                 final rows = (t['rows'] as List).map((r) => (r as List).map((c) => c.toString()).toList()).toList();
                 
                 return pw.Column(
                   crossAxisAlignment: pw.CrossAxisAlignment.start,
                   children: [
                     pw.Text((t['title'] ?? 'Data Table').toUpperCase(), style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                     pw.SizedBox(height: 5),
                     pw.Table.fromTextArray(
                       headers: headers,
                       data: rows,
                       headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
                       headerDecoration: const pw.BoxDecoration(color: PdfColors.blue),
                       cellAlignment: pw.Alignment.centerLeft,
                     ),
                     pw.SizedBox(height: 15),
                   ]
                 );
               }),
             pw.Footer(
               title: pw.Text('Generated by Cureonix AI', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey))
             )
           ];
         }
       )
     );

     try {
       final dir = await getApplicationDocumentsDirectory();
       final file = File('${dir.path}/cureonix_report_${DateTime.now().millisecondsSinceEpoch}.pdf');
       await file.writeAsBytes(await pdf.save());
       
       await OpenFilex.open(file.path);
       ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Report saved to ${file.path}')));
     } catch (e) {
       ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error saving PDF: $e')));
     }
  }
}
